### PR TITLE
Fixbram

### PR DESCRIPTION
**Pull request by nishihatapalmer**
bram wasn't testing to see if m < Q.

Causes an infinite loop if you search with bram for a pattern smaller than Q.

Note: bram is also failing some of the random tests at start and end of the text - but that's something else.

### CODE REVIEW

**Comment by ostafen** [comment]
Uhm, why are there so many changes in this PR? I guess only file changes should be Bram source file

**Comment by nishihatapalmer** [comment]
I think I submitted it as a branch off my previous PR instead of develop.

**Comment by ostafen** [comment]
Can you branch develop?

**Comment by nishihatapalmer** [comment]
Going to resubmit in a better PR with some other small fixes.

**Pull request closed without merging**
